FROM python:3.9

WORKDIR /example-repo-update

ENV AIRFLOW_HOME=/example-repo-update

RUN pip install apache-airflow
RUN pip install pytest

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY dags/ example-repo-update/dags/
COPY include/ example-repo-update/include/
COPY plugins/ example-repo-update/plugins/
COPY tests/ example-repo-update/tests/

CMD ["printenv"]