name: Astronomer CI - Deploy code

on:
  pull_request:
    branches:
      - main
env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
  DEPLOYMENT_ID: cle4p0fdt325082f05nco4rt6pu

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Create and Deploy to Deployment Preview
      shell: bash
      run: |
        # install the Astro CLI
        # curl -sSL https://install.astronomer.io | sudo bash -s

        DEPLOYMENT_NAME="$(./astro deployment inspect $DEPLOYMENT_ID --key configuration.name)"
        BRANCH_DEPLOYMENT_NAME=$BRANCH_NAME_$DEPLOYMENT_NAME

        # Create template of deployment to be copied with
        ./astro deployment inspect $DEPLOYMENT_ID --template > deployment-template.yaml # autmatically creates deployment-template.yaml file

        # Add name to deployment template file
        sed -i -e "s#name:#name: $BRANCH_DEPLOYMENT_NAME#" deployment-template.yaml
        
        # Create new deploymeent preview based on the deployment template file
        ./astro deployment create --deployment-file deployment-template.yaml

        # Deploy new code to the deployment preview 
        ./astro deploy --name $BRANCH_DEPLOYMENT_NAME